export const CENSORED_WORDS = [
  'blood',
  'knife',
  'nudity',
  'gun',
  'knife',
  'bomb',
  'explosive',
  'poison',
  'chemicals',
  'weapon',
  'alcohol',
  'tobacco',
  'cigarette',
  'drugs',
  'drug paraphernalia',
  'firearm',
  'ammunition',
  'syringe',
  'blade',
  'chainsaw',
  'axe',
  'machete',
  'switchblade',
  'grenade',
  'landmine',
  'rocket launcher',
  'flamethrower',
  'crossbow',
  'shuriken',
  'nunchaku',
  'brass knuckles',
  'knuckleduster'];
